"""Translations for the modernized web-client menu.

This module is intentionally independent from :mod:`dgt.translate`.  The DGT
translator produces hardware-sized strings; these labels are browser-only and
must never be truncated to a clock display width.

English is the complete reference catalog.  The other language dictionaries
override it.  A missing translation therefore remains usable in English while
making it straightforward for native speakers to edit one language in one
place.
"""

from __future__ import annotations

from string import Formatter


SUPPORTED_LANGUAGES = ("en", "de", "nl", "fr", "es", "it")


ENGLISH = {
    # Shared navigation and state
    "menu.title": "PicoChess Menu",
    "common.back": "Back",
    "common.close": "Close",
    "common.on": "On",
    "common.off": "Off",
    "common.none": "None",
    "common.all": "All",
    "common.engine": "Engine",
    "common.loading": "Loading…",
    "common.failed_to_load": "Failed to load",
    "common.please_wait": "Please wait",
    "common.unavailable": "Unavailable",
    "common.active": "Active",
    "common.shown": "Shown",
    "common.hidden": "Hidden",
    "common.yes": "Yes",
    "common.no": "No",
    "common.left": "Left",
    "common.right": "Right",
    "common.short": "Short",
    "common.long": "Long",
    "common.standard": "Standard",
    "common.white": "White",
    "common.black": "Black",
    "common.set": "Set",
    "state.game_in_progress": "Game in progress",
    "state.no_active_game": "No active game",
    "state.game_in_progress_marked": "● Game in progress",
    "state.no_active_game_marked": "○ No active game",
    "manual.open": "Open user manual",

    # Main tiles and panel titles
    "tile.mode": "Mode",
    "tile.engine": "Engine",
    "tile.time": "Time",
    "tile.engine_book": "Engine Book",
    "tile.tutor": "Tutor",
    "tile.position": "Position",
    "tile.game": "Game",
    "tile.system": "System",
    "tile.display": "Display",
    "tile.book_explorer": "Book Explorer",
    "tile.sound_on": "Sound On",
    "tile.display_summary": "Board · Pieces · Theme",
    "panel.playing_mode": "Playing Mode",
    "panel.time_control": "Time Control",
    "panel.picotutor": "PicoTutor",
    "panel.position_setup": "Position Setup",

    # Playing modes
    "mode.play": "Play",
    "mode.practice": "Practice",
    "mode.move_hints": "Enter Moves · Hints",
    "mode.move_score": "Enter Moves · Score",
    "mode.analysis": "Analysis",
    "mode.pgn_replay": "PGN Replay",
    "mode.hand_brain": "Hand & Brain",
    "mode.two_player": "Two-Player Game",
    "mode.remote": "Two-Player Remote",
    "mode.ponder_on": "Ponder On",
    "mode.brain": "Brain",
    "mode.hand": "Hand",
    "mode.replay": "Replay",
    "mode.replay_tutor": "Replay + Tutor Lines",
    "mode.choose_role": "Hand & Brain — choose role",
    "mode.choose_replay": "PGN Replay — choose replay type",
    "mode.return_to": "Return to {mode}",

    # Tutor
    "tutor.watcher": "Watcher",
    "tutor.coach": "Coach",
    "tutor.explorer": "Explorer",
    "tutor.comment": "Comment",
    "tutor.probability": "Probability",
    "tutor.hint": "Hint",
    "tutor.show_hint": "Show hint",
    "tutor.cpu": "Tutor CPU",
    "tutor.normal_threads": "Normal · 1×",
    "tutor.turbo_threads": "Turbo · {threads}×",
    "tutor.multipv": "MultiPV",
    "tutor.lines": "{count} lines",
    "tutor.target_depth": "Target depth",
    "tutor.depth": "d{depth}",
    "tutor.coach_mode": "Coach Mode",
    "tutor.comment_mode": "Comment Mode",
    "tutor.lift": "Lift",
    "tutor.deep_threads": "Deep Tutor threads",
    "tutor.deep_multipv": "Deep MultiPV",

    # Position setup
    "position.side_to_move": "Side to Move",
    "position.white_to_move": "White to move",
    "position.black_to_move": "Black to move",
    "position.board_orientation": "Board Orientation",
    "position.board_side": "Board Side",
    "position.white_bottom": "White on bottom",
    "position.black_bottom": "Black on bottom",
    "position.white_bottom_short": "White bottom",
    "position.black_bottom_short": "Black bottom",
    "position.chess960_mode": "Chess960 Mode",
    "position.standard_chess": "Standard chess",
    "position.chess960_frc": "Chess960 / FRC",
    "position.castling_rights": "Castling Rights",
    "position.castling": "Castling",
    "position.chess960": "Chess960",
    "position.standard_short": "Std",
    "position.sync_board": "Sync Board",
    "position.white_oo": "White O-O",
    "position.white_ooo": "White O-O-O",
    "position.black_oo": "Black O-O",
    "position.black_ooo": "Black O-O-O",
    "position.white_00": "White 0-0",
    "position.white_000": "White 0-0-0",
    "position.black_00": "Black 0-0",
    "position.black_000": "Black 0-0-0",
    "position.all_enabled": "All enabled",
    "position.scan": "Scan",
    "position.get_eboard": "Get eboard pos",
    "position.set_position": "Set Pos",
    "position.set_eboard": "Set eboard pos",
    "position.restoring": "Restoring…",
    "position.checkpoint_failed": "Checkpoint failed",
    "position.scanning": "Scanning…",
    "position.invalid": "Invalid",
    "position.invalid_position": "Invalid position",
    "position.check_board_retry": "Check board & retry",
    "position.scan_failed": "Scan failed",
    "position.check_connection": "Check connection",
    "position.setting": "Setting…",
    "position.reload_client": "Reload web client",
    "position.set_failed": "Set failed",
    "position.select_pgn_move": "Select PGN move",

    # Display
    "display.board": "Board",
    "display.pieces": "Pieces",
    "display.theme": "Theme",
    "display.clock_only": "Clock Only",
    "display.pgn_lines": "PGN Lines",
    "display.retro_touch": "Retro touch display",
    "display.board_color": "Board Color",
    "display.piece_set": "Piece Set",
    "display.ui_theme": "UI Theme",
    "display.blue": "Blue",
    "display.green": "Green",
    "display.metal": "Metal",
    "display.natural_wood": "Natural Wood",
    "display.newspaper": "Newspaper",
    "display.soft": "Soft",
    "display.wood": "Wood",
    "display.dark": "Dark",
    "display.light": "Light",
    "display.time": "Time",
    "display.auto": "Auto",

    # Engine and book pickers
    "engine.modern": "Modern",
    "engine.retro": "Retro",
    "engine.special": "Special",
    "engine.sort_order": "Sort Order",
    "engine.file_order": "File order",
    "engine.engine_name": "Engine name",
    "engine.manufacturer": "Manufacturer",
    "engine.level": "Level",
    "engine.no_engines": "No engines found",
    "book.select_engine": "Select Engine Book",
    "book.select_display": "Select Display Book",
    "book.no_books": "No books found",

    # Time controls
    "time.blitz": "Blitz",
    "time.fischer": "Fischer",
    "time.tournament": "Tournament",
    "time.fixed": "Fixed",
    "time.depth": "Depth",
    "time.nodes": "Nodes",
    "time.minutes_game": "Minutes / game",
    "time.min_game": "Min / game",
    "time.game_increment": "Game + increment",
    "time.game_increment_short": "Game + incr.",
    "time.tournament_format": "Tournament format",
    "time.moves_time": "Moves / time",
    "time.seconds_move": "Seconds / move",
    "time.sec_move": "Sec / move",
    "time.search_depth": "Search depth (plies)",
    "time.search_plies": "Search plies",
    "time.search_nodes": "Search nodes (k)",
    "time.nodes_k": "Nodes (k)",
    "time.value": "Value",

    # Game
    "game.new": "New Game",
    "game.hint": "Hint",
    "game.takeback": "Takeback",
    "game.save": "Save",
    "game.read": "Read",
    "game.end": "End Game",
    "game.alt_move": "Alt Move",
    "game.continue_last": "Cont Last",
    "game.switch_sides": "Switch Sides",
    "game.resign": "Resign",
    "game.move_now": "Move Now",
    "game.player": "Player",
    "game.download_pgn": "Download PGN",
    "game.upload_pgn": "Upload PGN",
    "game.start_confirm": "Start a new game?",
    "game.resign_confirm": "Resign the current game?",
    "game.player_info": "Player Info",
    "game.name": "Name",
    "game.player_name_prompt": "Player name:",
    "game.elo": "ELO",
    "game.elo_prompt": "ELO rating (0–3000):",
    "game.save_slot": "Save to Slot",
    "game.load_slot": "Load from Slot",
    "game.slot": "Slot {slot}",
    "game.last_game": "Last Game",
    "game.last_replay": "Last Replay",
    "game.set_result": "Set Result",
    "game.white_wins": "White wins",
    "game.black_wins": "Black wins",
    "game.draw": "Draw",
    "game.previous": "Prev",
    "game.next": "Next",

    # System
    "system.power": "Power",
    "system.info": "Info",
    "system.settings_file": "Picochess.ini",
    "system.phone_speaker": "Phone Speaker",
    "system.audio_backend": "Audio Backend",
    "system.dgt_beep": "DGT Beep",
    "system.language": "Language",
    "system.computer_voice": "Comp Voice",
    "system.user_voice": "User Voice",
    "system.computer_speaker": "Comp Speaker",
    "system.user_speaker": "User Speaker",
    "system.voice_speed": "Voice Speed",
    "system.volume": "Volume",
    "system.retro_speed": "Retro Speed",
    "system.retro_sound": "Retro Sound",
    "system.retro_display": "Retro Display",
    "system.retro_window": "Retro Window",
    "system.retro_info": "Retro Info",
    "system.preferences": "Preferences",
    "system.eboard": "EBoard",
    "system.eboard_type": "E-Board Type",
    "system.wifi_bt": "WiFi / BT",
    "system.shutdown": "Shutdown",
    "system.reboot": "Reboot",
    "system.exit": "Exit PicoChess",
    "system.update": "Update PicoChess",
    "system.shutdown_confirm": "Shut down the system?",
    "system.reboot_confirm": "Reboot the system?",
    "system.sound_beep": "Sound (Beep)",
    "system.some": "Some",
    "system.sample": "Sample",
    "system.no_eboard": "None",
    "system.toggle_hotspot": "Toggle Hotspot",
    "system.toggle_bt": "Toggle BT",
    "system.fix_bt": "Fix BT",
    "system.system_info": "System Info",
    "system.version": "Version",
    "system.git_status": "Git",
    "system.local_ip": "IP (local)",
    "system.external_ip": "IP (external)",
    "system.location": "Location",
    "system.battery": "Battery",
    "system.mute": "Mute",
    "system.no_voices_language": "No voices found for language {language}",
    "system.failed_voices": "Failed to load voices",
    "system.playback_rate": "Playback rate (0 = slowest, 9 = fastest)",
    "system.slow": "slow",
    "system.fast": "fast",
    "system.step_of": "Step {step} of 20",
    "system.max": "Max",
    "system.retro_playback_speed": "Retro engine playback speed",
    "system.engine_features": "Engine features: {features}",
    "system.windowed": "Windowed",
    "system.fullscreen": "Fullscreen",
    "system.audio_help": (
        "Technical setting. Saved for next PicoChess restart. Native is intended for "
        "Wayland/PipeWire and needs pipewire-alsa; if native has no sound, rerun the "
        "installer or see README."
    ),
    "system.native_backend": "Native (Wayland / PipeWire)",
    "system.native_backend_note": "Requires pipewire-alsa · restart PicoChess",
    "system.sox_backend": "SoX (X11 / legacy)",
    "system.sox_backend_note": "Older playback backend · restart PicoChess",
    "system.clock_side": "Clock Side",
    "system.notation": "Notation",
    "system.confirm": "Confirm",
    "system.capital": "Capital",
    "system.engine_name": "Engine Name",
    "system.ponder_seconds": "Ponder Sec",
    "system.phone_stream_on": "Remote PicoTalker stream on",
    "system.phone_stream_off": "Remote PicoTalker stream off",
    "system.phone_on": "Phone speaker on",
    "system.phone_off": "Phone speaker off",
}


GERMAN = {
    "menu.title": "PicoChess-Menü", "common.back": "Zurück", "common.close": "Schließen",
    "common.on": "Ein", "common.off": "Aus", "common.none": "Keine", "common.all": "Alle",
    "common.loading": "Laden…", "common.failed_to_load": "Laden fehlgeschlagen",
    "common.please_wait": "Bitte warten", "common.unavailable": "Nicht verfügbar",
    "common.active": "Aktiv", "common.shown": "Angezeigt", "common.hidden": "Ausgeblendet",
    "common.yes": "Ja", "common.no": "Nein", "common.left": "Links", "common.right": "Rechts",
    "common.short": "Kurz", "common.long": "Lang", "common.white": "Weiß", "common.black": "Schwarz",
    "state.game_in_progress": "Partie läuft", "state.no_active_game": "Keine aktive Partie",
    "state.game_in_progress_marked": "● Partie läuft", "state.no_active_game_marked": "○ Keine aktive Partie",
    "manual.open": "Benutzerhandbuch öffnen", "tile.mode": "Modus", "tile.time": "Bedenkzeit",
    "tile.engine_book": "Engine-Buch", "tile.position": "Stellung", "tile.game": "Partie",
    "tile.display": "Anzeige", "tile.book_explorer": "Buch-Explorer", "tile.sound_on": "Ton ein",
    "tile.display_summary": "Brett · Figuren · Design", "panel.playing_mode": "Spielmodus",
    "panel.time_control": "Zeitkontrolle", "panel.position_setup": "Stellung aufbauen",
    "mode.play": "Spielen", "mode.practice": "Training", "mode.move_hints": "Züge eingeben · Tipps",
    "mode.move_score": "Züge eingeben · Wertung", "mode.analysis": "Analyse",
    "mode.pgn_replay": "PGN-Wiedergabe", "mode.hand_brain": "Hand & Gehirn",
    "mode.two_player": "Zwei-Spieler-Partie", "mode.remote": "Zwei Spieler online",
    "mode.ponder_on": "Pondern ein", "mode.brain": "Gehirn", "mode.hand": "Hand",
    "mode.replay": "Wiedergabe", "mode.replay_tutor": "Wiedergabe + Tutorvarianten",
    "mode.choose_role": "Hand & Gehirn — Rolle wählen", "mode.choose_replay": "PGN — Wiedergabeart wählen",
    "mode.return_to": "Zurück zu {mode}", "tutor.watcher": "Beobachter", "tutor.coach": "Trainer",
    "tutor.comment": "Kommentar", "tutor.probability": "Wahrscheinlichkeit",
    "tutor.show_hint": "Tipp anzeigen", "tutor.cpu": "Tutor-CPU", "tutor.coach_mode": "Trainermodus",
    "tutor.comment_mode": "Kommentarmodus", "tutor.lift": "Anheben",
    "tutor.deep_threads": "Tiefe Tutor-Threads", "tutor.target_depth": "Zieltiefe",
    "position.side_to_move": "Am Zug", "position.white_to_move": "Weiß am Zug",
    "position.black_to_move": "Schwarz am Zug", "position.board_orientation": "Brettausrichtung",
    "position.board_side": "Brettseite", "position.white_bottom": "Weiß unten",
    "position.black_bottom": "Schwarz unten", "position.white_bottom_short": "Weiß unten",
    "position.black_bottom_short": "Schwarz unten", "position.chess960_mode": "Chess960-Modus",
    "position.standard_chess": "Standardschach", "position.castling_rights": "Rochaderechte",
    "position.all_enabled": "Alle aktiviert", "position.scan": "Scannen",
    "position.get_eboard": "E-Brett lesen", "position.set_position": "Stellung setzen",
    "position.set_eboard": "E-Brett-Stellung setzen", "position.restoring": "Wiederherstellen…",
    "position.checkpoint_failed": "Wiederherstellung fehlgeschlagen", "position.scanning": "Scannen…",
    "position.invalid": "Ungültig", "position.invalid_position": "Ungültige Stellung",
    "position.check_board_retry": "Brett prüfen und erneut versuchen", "position.scan_failed": "Scan fehlgeschlagen",
    "position.check_connection": "Verbindung prüfen", "position.setting": "Setzen…",
    "position.reload_client": "Webclient neu laden", "position.set_failed": "Setzen fehlgeschlagen",
    "position.select_pgn_move": "PGN-Zug auswählen", "display.board": "Brett",
    "display.pieces": "Figuren", "display.theme": "Design", "display.clock_only": "Nur Uhr",
    "display.pgn_lines": "PGN-Varianten", "display.retro_touch": "Retro-Touchanzeige",
    "display.board_color": "Brettfarbe", "display.piece_set": "Figurensatz",
    "display.ui_theme": "Oberflächendesign", "display.blue": "Blau", "display.green": "Grün",
    "display.natural_wood": "Naturholz", "display.newspaper": "Zeitung", "display.wood": "Holz",
    "display.dark": "Dunkel", "display.light": "Hell", "display.time": "Zeitgesteuert",
    "display.auto": "Automatisch", "engine.modern": "Modern", "engine.special": "Spezial",
    "engine.sort_order": "Sortierung", "engine.file_order": "Dateireihenfolge",
    "engine.engine_name": "Engine-Name", "engine.manufacturer": "Hersteller",
    "engine.level": "Stufe", "engine.no_engines": "Keine Engines gefunden",
    "book.select_engine": "Engine-Buch wählen", "book.select_display": "Anzeigebuch wählen",
    "book.no_books": "Keine Bücher gefunden", "time.tournament": "Turnier",
    "time.fixed": "Feste Zeit", "time.depth": "Suchtiefe", "time.nodes": "Knoten",
    "time.minutes_game": "Minuten / Partie", "time.min_game": "Min / Partie",
    "time.game_increment": "Partie + Inkrement", "time.game_increment_short": "Partie + Inkr.",
    "time.tournament_format": "Turnierformat", "time.moves_time": "Züge / Zeit",
    "time.seconds_move": "Sekunden / Zug", "time.sec_move": "Sek / Zug",
    "time.search_depth": "Suchtiefe (Halbzüge)", "time.search_plies": "Halbzüge",
    "time.search_nodes": "Suchknoten (k)", "time.value": "Wert", "game.new": "Neue Partie",
    "game.takeback": "Zug zurück", "game.save": "Speichern", "game.read": "Laden",
    "game.end": "Partie beenden", "game.alt_move": "Alternativzug", "game.continue_last": "Fortsetzen",
    "game.switch_sides": "Seiten wechseln", "game.resign": "Aufgeben", "game.move_now": "Jetzt ziehen",
    "game.player": "Spieler", "game.download_pgn": "PGN herunterladen", "game.upload_pgn": "PGN hochladen",
    "game.start_confirm": "Neue Partie starten?", "game.resign_confirm": "Aktuelle Partie aufgeben?",
    "game.player_info": "Spielerinfo", "game.name": "Name", "game.player_name_prompt": "Spielername:",
    "game.elo_prompt": "Elo-Zahl (0–3000):", "game.save_slot": "In Speicherplatz sichern",
    "game.load_slot": "Aus Speicherplatz laden", "game.slot": "Platz {slot}",
    "game.last_game": "Letzte Partie", "game.last_replay": "Letzte Wiedergabe",
    "game.set_result": "Ergebnis setzen", "game.white_wins": "Weiß gewinnt",
    "game.black_wins": "Schwarz gewinnt", "game.draw": "Remis", "game.previous": "Zurück",
    "game.next": "Weiter", "system.power": "Ein/Aus", "system.settings_file": "Picochess.ini",
    "system.phone_speaker": "Handy-Lautsprecher", "system.audio_backend": "Audio-Backend",
    "system.dgt_beep": "DGT-Signalton", "system.language": "Sprache",
    "system.computer_voice": "Computerstimme", "system.user_voice": "Spielerstimme",
    "system.computer_speaker": "Computer-Sprecher", "system.user_speaker": "Spieler-Sprecher",
    "system.voice_speed": "Sprechtempo", "system.volume": "Lautstärke",
    "system.retro_speed": "Retro-Geschwindigkeit", "system.retro_sound": "Retro-Ton",
    "system.retro_display": "Retro-Anzeige", "system.retro_window": "Retro-Fenster",
    "system.retro_info": "Retro-Info", "system.preferences": "Einstellungen",
    "system.eboard_type": "E-Brett-Typ", "system.wifi_bt": "WLAN / Bluetooth",
    "system.shutdown": "Herunterfahren", "system.reboot": "Neustart",
    "system.exit": "PicoChess beenden", "system.update": "PicoChess aktualisieren",
    "system.shutdown_confirm": "System herunterfahren?", "system.reboot_confirm": "System neu starten?",
    "system.sound_beep": "Ton (Signal)", "system.some": "Manche", "system.sample": "Testton",
    "system.toggle_hotspot": "Hotspot umschalten", "system.toggle_bt": "Bluetooth umschalten",
    "system.fix_bt": "Bluetooth reparieren", "system.system_info": "Systeminformationen",
    "system.version": "Version", "system.git_status": "Git", "system.local_ip": "IP (lokal)",
    "system.external_ip": "IP (extern)", "system.location": "Standort", "system.battery": "Akku",
    "system.mute": "Stumm",
    "system.no_voices_language": "Keine Stimmen für Sprache {language} gefunden",
    "system.failed_voices": "Stimmen konnten nicht geladen werden",
    "system.playback_rate": "Sprechtempo (0 = langsam, 9 = schnell)", "system.slow": "langsam",
    "system.fast": "schnell", "system.step_of": "Stufe {step} von 20",
    "system.retro_playback_speed": "Wiedergabetempo der Retro-Engine",
    "system.engine_features": "Engine-Funktionen: {features}", "system.windowed": "Fenster",
    "system.fullscreen": "Vollbild", "system.native_backend_note": "Benötigt pipewire-alsa · PicoChess neu starten",
    "system.sox_backend_note": "Älteres Audio-Backend · PicoChess neu starten",
    "system.clock_side": "Uhrseite", "system.notation": "Notation", "system.confirm": "Bestätigen",
    "system.capital": "Großbuchstaben", "system.engine_name": "Engine-Name",
    "system.ponder_seconds": "Ponder-Sekunden", "system.phone_stream_on": "PicoTalker-Stream zum Handy ein",
    "system.phone_stream_off": "PicoTalker-Stream zum Handy aus", "system.phone_on": "Handy-Lautsprecher ein",
    "system.phone_off": "Handy-Lautsprecher aus",
}


# Dutch, French, Spanish, and Italian use the same semantic keys.  Proper
# names and technical terms intentionally fall back to English when that is
# clearer than translating them.
DUTCH = {
    "menu.title": "PicoChess-menu", "common.back": "Terug", "common.close": "Sluiten",
    "common.on": "Aan", "common.off": "Uit", "common.none": "Geen", "common.all": "Alle",
    "common.loading": "Laden…", "common.failed_to_load": "Laden mislukt", "common.please_wait": "Even wachten",
    "common.unavailable": "Niet beschikbaar", "common.active": "Actief", "common.shown": "Getoond",
    "common.hidden": "Verborgen", "common.yes": "Ja", "common.no": "Nee", "common.left": "Links",
    "common.right": "Rechts", "common.short": "Kort", "common.long": "Lang",
    "state.game_in_progress": "Partij bezig", "state.no_active_game": "Geen actieve partij",
    "state.game_in_progress_marked": "● Partij bezig", "state.no_active_game_marked": "○ Geen actieve partij",
    "manual.open": "Handleiding openen", "tile.mode": "Modus", "tile.time": "Tijd",
    "tile.engine_book": "Engineboek", "tile.position": "Stelling", "tile.game": "Partij",
    "tile.system": "Systeem", "tile.display": "Weergave", "tile.book_explorer": "Boekverkenner",
    "tile.sound_on": "Geluid aan", "tile.display_summary": "Bord · Stukken · Thema",
    "panel.playing_mode": "Speelmodus", "panel.time_control": "Tijdcontrole",
    "panel.position_setup": "Stelling instellen", "mode.play": "Spelen", "mode.practice": "Oefenen",
    "mode.move_hints": "Zetten invoeren · Tips", "mode.move_score": "Zetten invoeren · Score",
    "mode.analysis": "Analyse", "mode.pgn_replay": "PGN afspelen", "mode.hand_brain": "Hand & Brein",
    "mode.two_player": "Partij voor twee", "mode.remote": "Twee spelers op afstand",
    "mode.brain": "Brein", "mode.replay": "Afspelen", "mode.replay_tutor": "Afspelen + Tutor-lijnen",
    "mode.choose_role": "Hand & Brein — kies rol", "mode.choose_replay": "PGN — kies afspeeltype",
    "mode.return_to": "Terug naar {mode}", "tutor.watcher": "Bewaker", "tutor.coach": "Coach",
    "tutor.comment": "Commentaar", "tutor.probability": "Kans", "tutor.show_hint": "Toon hint",
    "tutor.coach_mode": "Coachmodus", "tutor.comment_mode": "Commentaarmodus", "tutor.lift": "Optillen",
    "position.side_to_move": "Aan zet", "position.white_to_move": "Wit aan zet",
    "position.black_to_move": "Zwart aan zet", "position.board_orientation": "Bordoriëntatie",
    "position.board_side": "Bordzijde", "position.white_bottom": "Wit onder",
    "position.black_bottom": "Zwart onder", "position.white_bottom_short": "Wit onder",
    "position.black_bottom_short": "Zwart onder", "position.chess960_mode": "Chess960-modus",
    "position.standard_chess": "Standaardschaak", "position.castling_rights": "Rokaderechten",
    "position.all_enabled": "Alles ingeschakeld", "position.scan": "Scannen",
    "position.get_eboard": "E-bord lezen", "position.set_position": "Stelling zetten",
    "position.set_eboard": "E-bordstelling zetten", "position.restoring": "Herstellen…",
    "position.checkpoint_failed": "Herstelpunt mislukt", "position.scanning": "Scannen…",
    "position.invalid": "Ongeldig", "position.invalid_position": "Ongeldige stelling",
    "position.check_board_retry": "Controleer bord en probeer opnieuw", "position.scan_failed": "Scan mislukt",
    "position.check_connection": "Controleer verbinding", "position.setting": "Instellen…",
    "position.reload_client": "Webclient herladen", "position.set_failed": "Instellen mislukt",
    "display.board": "Bord", "display.pieces": "Stukken", "display.theme": "Thema",
    "display.clock_only": "Alleen klok", "display.pgn_lines": "PGN-lijnen",
    "display.board_color": "Bordkleur", "display.piece_set": "Stukkenset", "display.ui_theme": "UI-thema",
    "display.blue": "Blauw", "display.green": "Groen", "display.natural_wood": "Natuurlijk hout",
    "display.newspaper": "Krant", "display.soft": "Zacht", "display.wood": "Hout",
    "display.dark": "Donker", "display.light": "Licht", "display.time": "Tijd", "display.auto": "Automatisch",
    "engine.modern": "Modern", "engine.special": "Speciaal", "engine.sort_order": "Sorteervolgorde",
    "engine.file_order": "Bestandsvolgorde", "engine.engine_name": "Enginenaam",
    "engine.manufacturer": "Fabrikant", "engine.level": "Niveau", "engine.no_engines": "Geen engines gevonden",
    "book.select_engine": "Engineboek kiezen", "book.select_display": "Weergaveboek kiezen",
    "book.no_books": "Geen boeken gevonden", "time.tournament": "Toernooi", "time.fixed": "Vaste tijd",
    "time.depth": "Zoekdiepte", "time.nodes": "Knooppunten", "time.minutes_game": "Minuten / partij",
    "time.game_increment": "Partij + increment", "time.tournament_format": "Toernooiformaat",
    "time.moves_time": "Zetten / tijd", "time.seconds_move": "Seconden / zet",
    "time.search_depth": "Zoekdiepte (ply)", "time.search_nodes": "Zoekknooppunten (k)",
    "game.new": "Nieuwe partij", "game.takeback": "Zet terug", "game.save": "Opslaan",
    "game.read": "Laden", "game.end": "Partij beëindigen", "game.alt_move": "Andere zet",
    "game.continue_last": "Laatste voortzetten", "game.switch_sides": "Kanten wisselen",
    "game.resign": "Opgeven", "game.move_now": "Zet nu", "game.player": "Speler",
    "game.download_pgn": "PGN downloaden", "game.upload_pgn": "PGN uploaden",
    "game.start_confirm": "Nieuwe partij starten?", "game.resign_confirm": "Huidige partij opgeven?",
    "game.player_info": "Spelerinformatie", "game.player_name_prompt": "Spelernaam:",
    "game.elo_prompt": "ELO-rating (0–3000):", "game.save_slot": "Opslaan in vak",
    "game.load_slot": "Laden uit vak", "game.slot": "Vak {slot}", "game.last_game": "Laatste partij",
    "game.last_replay": "Laatste replay", "game.set_result": "Resultaat instellen",
    "game.white_wins": "Wit wint", "game.black_wins": "Zwart wint", "game.draw": "Remise",
    "game.previous": "Vorige", "game.next": "Volgende", "system.power": "Voeding",
    "system.phone_speaker": "Telefoonluidspreker", "system.audio_backend": "Audio-backend",
    "system.dgt_beep": "DGT-piep", "system.language": "Taal", "system.computer_voice": "Computerstem",
    "system.user_voice": "Spelerstem", "system.voice_speed": "Stemsnelheid", "system.volume": "Volume",
    "system.retro_speed": "Retrosnelheid", "system.retro_sound": "Retrogeluid",
    "system.retro_display": "Retroweergave", "system.retro_window": "Retrovenster",
    "system.preferences": "Voorkeuren", "system.eboard_type": "E-bordtype", "system.wifi_bt": "Wifi / Bluetooth",
    "system.shutdown": "Afsluiten", "system.reboot": "Herstarten", "system.exit": "PicoChess afsluiten",
    "system.update": "PicoChess bijwerken", "system.shutdown_confirm": "Systeem afsluiten?",
    "system.reboot_confirm": "Systeem herstarten?", "system.sound_beep": "Geluid (piep)",
    "system.some": "Sommige", "system.sample": "Voorbeeld", "system.toggle_hotspot": "Hotspot omschakelen",
    "system.toggle_bt": "Bluetooth omschakelen", "system.fix_bt": "Bluetooth herstellen",
    "system.system_info": "Systeeminformatie", "system.failed_voices": "Stemmen laden mislukt",
    "system.version": "Versie", "system.git_status": "Git", "system.local_ip": "IP (lokaal)",
    "system.external_ip": "IP (extern)", "system.location": "Locatie", "system.battery": "Batterij",
    "system.mute": "Dempen",
    "system.playback_rate": "Afspeelsnelheid (0 = langzaamst, 9 = snelst)", "system.slow": "langzaam",
    "system.fast": "snel", "system.step_of": "Stap {step} van 20",
    "system.retro_playback_speed": "Afspeelsnelheid retro-engine",
    "system.engine_features": "Enginefuncties: {features}",
    "system.windowed": "Venster", "system.fullscreen": "Volledig scherm", "system.clock_side": "Klokzijde",
    "system.notation": "Notatie", "system.confirm": "Bevestigen", "system.capital": "Hoofdletters",
    "system.engine_name": "Enginenaam", "system.ponder_seconds": "Ponderseconden",
    "system.phone_stream_on": "PicoTalker-stream naar telefoon aan",
    "system.phone_stream_off": "PicoTalker-stream naar telefoon uit",
}


FRENCH = {
    "menu.title": "Menu PicoChess", "common.back": "Retour", "common.close": "Fermer",
    "common.on": "Activé", "common.off": "Désactivé", "common.none": "Aucun", "common.all": "Tous",
    "common.loading": "Chargement…", "common.failed_to_load": "Échec du chargement",
    "common.please_wait": "Veuillez patienter", "common.unavailable": "Indisponible",
    "common.active": "Actif", "common.shown": "Affiché", "common.hidden": "Masqué",
    "common.yes": "Oui", "common.no": "Non", "common.left": "Gauche", "common.right": "Droite",
    "common.short": "Courte", "common.long": "Longue", "state.game_in_progress": "Partie en cours",
    "state.no_active_game": "Aucune partie active", "state.game_in_progress_marked": "● Partie en cours",
    "state.no_active_game_marked": "○ Aucune partie active", "manual.open": "Ouvrir le manuel utilisateur",
    "tile.mode": "Mode", "tile.time": "Temps", "tile.engine_book": "Livre moteur",
    "tile.position": "Position", "tile.game": "Partie", "tile.system": "Système",
    "tile.display": "Affichage", "tile.book_explorer": "Explorateur de livres",
    "tile.sound_on": "Son activé", "tile.display_summary": "Échiquier · Pièces · Thème",
    "panel.playing_mode": "Mode de jeu", "panel.time_control": "Cadence",
    "panel.position_setup": "Configurer la position", "mode.play": "Jouer", "mode.practice": "Entraînement",
    "mode.move_hints": "Saisir les coups · Conseils", "mode.move_score": "Saisir les coups · Score",
    "mode.analysis": "Analyse", "mode.pgn_replay": "Relecture PGN", "mode.hand_brain": "Main & Cerveau",
    "mode.two_player": "Partie à deux", "mode.remote": "Deux joueurs à distance",
    "mode.brain": "Cerveau", "mode.hand": "Main", "mode.replay": "Relecture",
    "mode.replay_tutor": "Relecture + variantes du tuteur", "mode.choose_role": "Main & Cerveau — choisir le rôle",
    "mode.choose_replay": "PGN — choisir le type de relecture", "mode.return_to": "Retour à {mode}",
    "tutor.watcher": "Observateur", "tutor.coach": "Entraîneur", "tutor.explorer": "Explorateur",
    "tutor.comment": "Commentaire", "tutor.probability": "Probabilité", "tutor.show_hint": "Afficher un conseil",
    "tutor.coach_mode": "Mode entraîneur", "tutor.comment_mode": "Mode commentaire", "tutor.lift": "Soulever",
    "position.side_to_move": "Trait", "position.white_to_move": "Aux blancs", "position.black_to_move": "Aux noirs",
    "position.board_orientation": "Orientation de l’échiquier", "position.board_side": "Côté de l’échiquier",
    "position.white_bottom": "Blancs en bas", "position.black_bottom": "Noirs en bas",
    "position.white_bottom_short": "Blancs en bas", "position.black_bottom_short": "Noirs en bas",
    "position.chess960_mode": "Mode Chess960", "position.standard_chess": "Échecs standard",
    "position.castling_rights": "Droits de roque", "position.all_enabled": "Tous activés",
    "position.scan": "Scanner", "position.get_eboard": "Lire l’échiquier",
    "position.set_position": "Définir position",
    "position.set_eboard": "Définir sur l’échiquier", "position.restoring": "Restauration…",
    "position.checkpoint_failed": "Échec de la restauration", "position.scanning": "Analyse…",
    "position.invalid": "Invalide", "position.invalid_position": "Position invalide",
    "position.check_board_retry": "Vérifiez l’échiquier et réessayez", "position.scan_failed": "Échec du scan",
    "position.check_connection": "Vérifiez la connexion", "position.setting": "Application…",
    "position.reload_client": "Rechargez le client web", "position.set_failed": "Échec de l’application",
    "display.board": "Échiquier", "display.pieces": "Pièces", "display.theme": "Thème",
    "display.clock_only": "Horloge seule", "display.pgn_lines": "Variantes PGN",
    "display.board_color": "Couleur de l’échiquier", "display.piece_set": "Jeu de pièces",
    "display.ui_theme": "Thème de l’interface", "display.blue": "Bleu", "display.green": "Vert",
    "display.natural_wood": "Bois naturel", "display.newspaper": "Journal", "display.soft": "Doux",
    "display.wood": "Bois", "display.dark": "Sombre", "display.light": "Clair",
    "display.time": "Selon l’heure", "display.auto": "Automatique", "engine.modern": "Moderne",
    "engine.special": "Spécial", "engine.sort_order": "Ordre de tri", "engine.file_order": "Ordre du fichier",
    "engine.engine_name": "Nom du moteur", "engine.manufacturer": "Fabricant", "engine.level": "Niveau",
    "engine.no_engines": "Aucun moteur trouvé", "book.select_engine": "Choisir le livre moteur",
    "book.select_display": "Choisir le livre affiché", "book.no_books": "Aucun livre trouvé",
    "time.tournament": "Tournoi", "time.fixed": "Temps fixe", "time.depth": "Profondeur",
    "time.nodes": "Nœuds", "time.minutes_game": "Minutes / partie", "time.game_increment": "Partie + incrément",
    "time.tournament_format": "Format tournoi", "time.moves_time": "Coups / temps",
    "time.seconds_move": "Secondes / coup", "time.search_depth": "Profondeur (demi-coups)",
    "time.search_nodes": "Nœuds de recherche (k)", "game.new": "Nouvelle partie",
    "game.takeback": "Reprendre le coup", "game.save": "Enregistrer", "game.read": "Charger",
    "game.end": "Terminer la partie", "game.alt_move": "Autre coup", "game.continue_last": "Continuer la dernière",
    "game.switch_sides": "Inverser les côtés", "game.resign": "Abandonner", "game.move_now": "Jouer maintenant",
    "game.player": "Joueur", "game.download_pgn": "Télécharger le PGN", "game.upload_pgn": "Importer un PGN",
    "game.start_confirm": "Commencer une nouvelle partie ?", "game.resign_confirm": "Abandonner la partie en cours ?",
    "game.player_info": "Informations joueur", "game.player_name_prompt": "Nom du joueur :",
    "game.elo_prompt": "Classement Elo (0–3000) :", "game.save_slot": "Enregistrer dans l’emplacement",
    "game.load_slot": "Charger depuis l’emplacement", "game.slot": "Emplacement {slot}",
    "game.last_game": "Dernière partie", "game.last_replay": "Dernière relecture",
    "game.set_result": "Définir le résultat", "game.white_wins": "Les blancs gagnent",
    "game.black_wins": "Les noirs gagnent", "game.draw": "Nulle", "game.previous": "Précédent",
    "game.next": "Suivant", "system.power": "Alimentation", "system.phone_speaker": "Haut-parleur du téléphone",
    "system.audio_backend": "Moteur audio", "system.dgt_beep": "Bip DGT", "system.language": "Langue",
    "system.computer_voice": "Voix ordinateur", "system.user_voice": "Voix joueur",
    "system.voice_speed": "Vitesse de la voix", "system.volume": "Volume",
    "system.retro_speed": "Vitesse rétro", "system.retro_sound": "Son rétro",
    "system.retro_display": "Affichage rétro", "system.retro_window": "Fenêtre rétro",
    "system.preferences": "Préférences", "system.eboard_type": "Type d’échiquier électronique",
    "system.wifi_bt": "Wi-Fi / Bluetooth", "system.shutdown": "Éteindre", "system.reboot": "Redémarrer",
    "system.exit": "Quitter PicoChess", "system.update": "Mettre PicoChess à jour",
    "system.shutdown_confirm": "Éteindre le système ?", "system.reboot_confirm": "Redémarrer le système ?",
    "system.sound_beep": "Son (bip)", "system.some": "Certains", "system.sample": "Échantillon",
    "system.toggle_hotspot": "Basculer le point d’accès", "system.toggle_bt": "Basculer Bluetooth",
    "system.fix_bt": "Réparer Bluetooth", "system.system_info": "Informations système",
    "system.version": "Version", "system.git_status": "Git", "system.local_ip": "IP (locale)",
    "system.external_ip": "IP (externe)", "system.location": "Emplacement", "system.battery": "Batterie",
    "system.mute": "Muet",
    "system.failed_voices": "Échec du chargement des voix",
    "system.playback_rate": "Vitesse de lecture (0 = lente, 9 = rapide)", "system.slow": "lent",
    "system.fast": "rapide", "system.step_of": "Étape {step} sur 20",
    "system.retro_playback_speed": "Vitesse de lecture du moteur rétro",
    "system.engine_features": "Fonctions du moteur : {features}", "system.windowed": "Fenêtré",
    "system.fullscreen": "Plein écran", "system.clock_side": "Côté de l’horloge",
    "system.notation": "Notation", "system.confirm": "Confirmer", "system.capital": "Majuscules",
    "system.engine_name": "Nom du moteur", "system.ponder_seconds": "Secondes de réflexion",
}


SPANISH = {
    "menu.title": "Menú PicoChess", "common.back": "Atrás", "common.close": "Cerrar",
    "common.on": "Sí", "common.off": "No", "common.none": "Ninguno", "common.all": "Todos",
    "common.loading": "Cargando…", "common.failed_to_load": "Error al cargar", "common.please_wait": "Espere",
    "common.unavailable": "No disponible", "common.active": "Activo", "common.shown": "Visible",
    "common.hidden": "Oculto", "common.yes": "Sí", "common.no": "No", "common.left": "Izquierda",
    "common.right": "Derecha", "common.short": "Corta", "common.long": "Larga",
    "state.game_in_progress": "Partida en curso", "state.no_active_game": "No hay partida activa",
    "state.game_in_progress_marked": "● Partida en curso",
    "state.no_active_game_marked": "○ No hay partida activa",
    "manual.open": "Abrir manual de usuario", "tile.mode": "Modo", "tile.time": "Tiempo",
    "tile.engine_book": "Libro del motor", "tile.position": "Posición", "tile.game": "Partida",
    "tile.system": "Sistema", "tile.display": "Pantalla", "tile.book_explorer": "Explorador de libros",
    "tile.sound_on": "Sonido activo", "tile.display_summary": "Tablero · Piezas · Tema",
    "panel.playing_mode": "Modo de juego", "panel.time_control": "Control de tiempo",
    "panel.position_setup": "Configurar posición", "mode.play": "Jugar", "mode.practice": "Práctica",
    "mode.move_hints": "Introducir jugadas · Pistas", "mode.move_score": "Introducir jugadas · Eval.",
    "mode.analysis": "Análisis", "mode.pgn_replay": "Reproducir PGN", "mode.hand_brain": "Mano y Cerebro",
    "mode.two_player": "Partida para dos", "mode.remote": "Dos jugadores remotos",
    "mode.brain": "Cerebro", "mode.hand": "Mano", "mode.replay": "Reproducir",
    "mode.replay_tutor": "Reproducir + líneas del tutor", "mode.choose_role": "Mano y Cerebro — elige rol",
    "mode.choose_replay": "PGN — elige tipo de reproducción", "mode.return_to": "Volver a {mode}",
    "tutor.watcher": "Vigilante", "tutor.coach": "Entrenador", "tutor.explorer": "Explorador",
    "tutor.comment": "Comentario", "tutor.probability": "Probabilidad", "tutor.show_hint": "Mostrar pista",
    "tutor.coach_mode": "Modo entrenador", "tutor.comment_mode": "Modo comentario", "tutor.lift": "Levantar",
    "position.side_to_move": "Turno", "position.white_to_move": "Juegan blancas",
    "position.black_to_move": "Juegan negras", "position.board_orientation": "Orientación del tablero",
    "position.board_side": "Lado del tablero", "position.white_bottom": "Blancas abajo",
    "position.black_bottom": "Negras abajo", "position.white_bottom_short": "Blancas abajo",
    "position.black_bottom_short": "Negras abajo", "position.chess960_mode": "Modo Chess960",
    "position.standard_chess": "Ajedrez estándar", "position.castling_rights": "Derechos de enroque",
    "position.all_enabled": "Todos activados", "position.scan": "Escanear",
    "position.get_eboard": "Leer tablero electrónico", "position.set_position": "Fijar posición",
    "position.set_eboard": "Fijar en tablero electrónico", "position.restoring": "Restaurando…",
    "position.checkpoint_failed": "Error al restaurar", "position.scanning": "Escaneando…",
    "position.invalid": "No válida", "position.invalid_position": "Posición no válida",
    "position.check_board_retry": "Revise el tablero e inténtelo de nuevo",
    "position.scan_failed": "Error de escaneo",
    "position.check_connection": "Revise la conexión", "position.setting": "Aplicando…",
    "position.reload_client": "Recargue el cliente web", "position.set_failed": "Error al aplicar",
    "display.board": "Tablero", "display.pieces": "Piezas", "display.theme": "Tema",
    "display.clock_only": "Solo reloj", "display.pgn_lines": "Líneas PGN",
    "display.board_color": "Color del tablero", "display.piece_set": "Juego de piezas",
    "display.ui_theme": "Tema de interfaz", "display.blue": "Azul", "display.green": "Verde",
    "display.natural_wood": "Madera natural", "display.newspaper": "Periódico", "display.soft": "Suave",
    "display.wood": "Madera", "display.dark": "Oscuro", "display.light": "Claro",
    "display.time": "Según la hora", "display.auto": "Automático", "engine.modern": "Moderno",
    "engine.special": "Especial", "engine.sort_order": "Orden", "engine.file_order": "Orden del archivo",
    "engine.engine_name": "Nombre del motor", "engine.manufacturer": "Fabricante", "engine.level": "Nivel",
    "engine.no_engines": "No se encontraron motores", "book.select_engine": "Elegir libro del motor",
    "book.select_display": "Elegir libro de pantalla", "book.no_books": "No se encontraron libros",
    "time.tournament": "Torneo", "time.fixed": "Tiempo fijo", "time.depth": "Profundidad",
    "time.nodes": "Nodos", "time.minutes_game": "Minutos / partida", "time.game_increment": "Partida + incremento",
    "time.tournament_format": "Formato de torneo", "time.moves_time": "Jugadas / tiempo",
    "time.seconds_move": "Segundos / jugada", "time.search_depth": "Profundidad (semijugadas)",
    "time.search_nodes": "Nodos de búsqueda (k)", "game.new": "Nueva partida", "game.takeback": "Deshacer jugada",
    "game.save": "Guardar", "game.read": "Cargar", "game.end": "Finalizar partida",
    "game.alt_move": "Jugada alternativa", "game.continue_last": "Continuar última",
    "game.switch_sides": "Cambiar bandos", "game.resign": "Rendirse", "game.move_now": "Mover ahora",
    "game.player": "Jugador", "game.download_pgn": "Descargar PGN", "game.upload_pgn": "Subir PGN",
    "game.start_confirm": "¿Iniciar una nueva partida?", "game.resign_confirm": "¿Rendirse en la partida actual?",
    "game.player_info": "Datos del jugador", "game.player_name_prompt": "Nombre del jugador:",
    "game.elo_prompt": "ELO (0–3000):", "game.save_slot": "Guardar en espacio",
    "game.load_slot": "Cargar desde espacio", "game.slot": "Espacio {slot}", "game.last_game": "Última partida",
    "game.last_replay": "Última reproducción", "game.set_result": "Fijar resultado",
    "game.white_wins": "Ganan las blancas", "game.black_wins": "Ganan las negras", "game.draw": "Tablas",
    "game.previous": "Anterior", "game.next": "Siguiente", "system.power": "Alimentación",
    "system.phone_speaker": "Altavoz del teléfono", "system.audio_backend": "Sistema de audio",
    "system.dgt_beep": "Pitido DGT", "system.language": "Idioma", "system.computer_voice": "Voz del ordenador",
    "system.user_voice": "Voz del jugador", "system.voice_speed": "Velocidad de voz", "system.volume": "Volumen",
    "system.retro_speed": "Velocidad retro", "system.retro_sound": "Sonido retro",
    "system.retro_display": "Pantalla retro", "system.retro_window": "Ventana retro",
    "system.preferences": "Preferencias", "system.eboard_type": "Tipo de tablero electrónico",
    "system.wifi_bt": "Wi-Fi / Bluetooth", "system.shutdown": "Apagar", "system.reboot": "Reiniciar",
    "system.exit": "Salir de PicoChess", "system.update": "Actualizar PicoChess",
    "system.shutdown_confirm": "¿Apagar el sistema?", "system.reboot_confirm": "¿Reiniciar el sistema?",
    "system.sound_beep": "Sonido (pitido)", "system.some": "Algunos", "system.sample": "Muestra",
    "system.toggle_hotspot": "Alternar punto de acceso", "system.toggle_bt": "Alternar Bluetooth",
    "system.fix_bt": "Reparar Bluetooth", "system.system_info": "Información del sistema",
    "system.version": "Versión", "system.git_status": "Git", "system.local_ip": "IP (local)",
    "system.external_ip": "IP (externa)", "system.location": "Ubicación", "system.battery": "Batería",
    "system.mute": "Silenciar",
    "system.failed_voices": "Error al cargar las voces",
    "system.playback_rate": "Velocidad de reproducción (0 = mínima, 9 = máxima)", "system.slow": "lento",
    "system.fast": "rápido", "system.step_of": "Paso {step} de 20",
    "system.retro_playback_speed": "Velocidad de reproducción del motor retro",
    "system.engine_features": "Funciones del motor: {features}", "system.windowed": "Ventana",
    "system.fullscreen": "Pantalla completa", "system.clock_side": "Lado del reloj",
    "system.notation": "Notación", "system.confirm": "Confirmar", "system.capital": "Mayúsculas",
    "system.engine_name": "Nombre del motor", "system.ponder_seconds": "Segundos de ponderación",
}


ITALIAN = {
    "menu.title": "Menu PicoChess", "common.back": "Indietro", "common.close": "Chiudi",
    "common.on": "Attivo", "common.off": "Disattivo", "common.none": "Nessuno", "common.all": "Tutti",
    "common.loading": "Caricamento…", "common.failed_to_load": "Caricamento fallito",
    "common.please_wait": "Attendere", "common.unavailable": "Non disponibile", "common.active": "Attivo",
    "common.shown": "Visibili", "common.hidden": "Nascoste", "common.yes": "Sì", "common.no": "No",
    "common.left": "Sinistra", "common.right": "Destra", "common.short": "Corta", "common.long": "Lunga",
    "state.game_in_progress": "Partita in corso", "state.no_active_game": "Nessuna partita attiva",
    "state.game_in_progress_marked": "● Partita in corso",
    "state.no_active_game_marked": "○ Nessuna partita attiva",
    "manual.open": "Apri il manuale utente", "tile.mode": "Modalità", "tile.time": "Tempo",
    "tile.engine_book": "Libro motore", "tile.position": "Posizione", "tile.game": "Partita",
    "tile.system": "Sistema", "tile.display": "Schermo", "tile.book_explorer": "Esplora libro",
    "tile.sound_on": "Audio attivo", "tile.display_summary": "Scacchiera · Pezzi · Tema",
    "panel.playing_mode": "Modalità di gioco", "panel.time_control": "Controllo del tempo",
    "panel.position_setup": "Imposta posizione", "mode.play": "Gioca", "mode.practice": "Allenamento",
    "mode.move_hints": "Inserisci mosse · Suggerimenti", "mode.move_score": "Inserisci mosse · Valutazione",
    "mode.analysis": "Analisi", "mode.pgn_replay": "Riproduci PGN", "mode.hand_brain": "Mano e Cervello",
    "mode.two_player": "Partita a due", "mode.remote": "Due giocatori remoti",
    "mode.brain": "Cervello", "mode.hand": "Mano", "mode.replay": "Riproduzione",
    "mode.replay_tutor": "Riproduzione + linee Tutor", "mode.choose_role": "Mano e Cervello — scegli ruolo",
    "mode.choose_replay": "PGN — scegli tipo di riproduzione", "mode.return_to": "Torna a {mode}",
    "tutor.watcher": "Osservatore", "tutor.coach": "Allenatore", "tutor.explorer": "Esplora",
    "tutor.comment": "Commento", "tutor.probability": "Probabilità", "tutor.show_hint": "Mostra suggerimento",
    "tutor.coach_mode": "Modalità allenatore", "tutor.comment_mode": "Modalità commento", "tutor.lift": "Solleva",
    "position.side_to_move": "Lato al tratto", "position.white_to_move": "Muove il Bianco",
    "position.black_to_move": "Muove il Nero", "position.board_orientation": "Orientamento scacchiera",
    "position.board_side": "Lato scacchiera", "position.white_bottom": "Bianco in basso",
    "position.black_bottom": "Nero in basso", "position.white_bottom_short": "Bianco in basso",
    "position.black_bottom_short": "Nero in basso", "position.chess960_mode": "Modalità Chess960",
    "position.standard_chess": "Scacchi standard", "position.castling_rights": "Diritti di arrocco",
    "position.all_enabled": "Tutti attivi", "position.scan": "Scansiona",
    "position.get_eboard": "Leggi scacchiera elettronica", "position.set_position": "Imposta posizione",
    "position.set_eboard": "Imposta sulla scacchiera", "position.restoring": "Ripristino…",
    "position.checkpoint_failed": "Ripristino fallito", "position.scanning": "Scansione…",
    "position.invalid": "Non valida", "position.invalid_position": "Posizione non valida",
    "position.check_board_retry": "Controlla la scacchiera e riprova", "position.scan_failed": "Scansione fallita",
    "position.check_connection": "Controlla la connessione", "position.setting": "Impostazione…",
    "position.reload_client": "Ricarica il client web", "position.set_failed": "Impostazione fallita",
    "display.board": "Scacchiera", "display.pieces": "Pezzi", "display.theme": "Tema",
    "display.clock_only": "Solo orologio", "display.pgn_lines": "Linee PGN",
    "display.board_color": "Colore scacchiera", "display.piece_set": "Set di pezzi",
    "display.ui_theme": "Tema interfaccia", "display.blue": "Blu", "display.green": "Verde",
    "display.natural_wood": "Legno naturale", "display.newspaper": "Giornale", "display.soft": "Tenue",
    "display.wood": "Legno", "display.dark": "Scuro", "display.light": "Chiaro",
    "display.time": "In base all’ora", "display.auto": "Automatico", "engine.modern": "Moderni",
    "engine.special": "Speciali", "engine.sort_order": "Ordinamento", "engine.file_order": "Ordine del file",
    "engine.engine_name": "Nome motore", "engine.manufacturer": "Produttore", "engine.level": "Livello",
    "engine.no_engines": "Nessun motore trovato", "book.select_engine": "Scegli libro motore",
    "book.select_display": "Scegli libro da mostrare", "book.no_books": "Nessun libro trovato",
    "time.tournament": "Torneo", "time.fixed": "Tempo fisso", "time.depth": "Profondità",
    "time.nodes": "Nodi", "time.minutes_game": "Minuti / partita", "time.game_increment": "Partita + incremento",
    "time.tournament_format": "Formato torneo", "time.moves_time": "Mosse / tempo",
    "time.seconds_move": "Secondi / mossa", "time.search_depth": "Profondità (semimosse)",
    "time.search_nodes": "Nodi di ricerca (k)", "game.new": "Nuova partita", "game.takeback": "Annulla mossa",
    "game.save": "Salva", "game.read": "Carica", "game.end": "Termina partita",
    "game.alt_move": "Mossa alternativa", "game.continue_last": "Continua ultima",
    "game.switch_sides": "Cambia lato", "game.resign": "Abbandona", "game.move_now": "Muovi ora",
    "game.player": "Giocatore", "game.download_pgn": "Scarica PGN", "game.upload_pgn": "Carica PGN",
    "game.start_confirm": "Iniziare una nuova partita?", "game.resign_confirm": "Abbandonare la partita attuale?",
    "game.player_info": "Dati giocatore", "game.player_name_prompt": "Nome giocatore:",
    "game.elo_prompt": "Punteggio ELO (0–3000):", "game.save_slot": "Salva nello slot",
    "game.load_slot": "Carica dallo slot", "game.slot": "Slot {slot}", "game.last_game": "Ultima partita",
    "game.last_replay": "Ultima riproduzione", "game.set_result": "Imposta risultato",
    "game.white_wins": "Vince il Bianco", "game.black_wins": "Vince il Nero", "game.draw": "Patta",
    "game.previous": "Precedente", "game.next": "Successivo", "system.power": "Alimentazione",
    "system.phone_speaker": "Altoparlante telefono", "system.audio_backend": "Backend audio",
    "system.dgt_beep": "Segnale DGT", "system.language": "Lingua", "system.computer_voice": "Voce computer",
    "system.user_voice": "Voce giocatore", "system.voice_speed": "Velocità voce", "system.volume": "Volume",
    "system.retro_speed": "Velocità retro", "system.retro_sound": "Audio retro",
    "system.retro_display": "Schermo retro", "system.retro_window": "Finestra retro",
    "system.preferences": "Preferenze", "system.eboard_type": "Tipo scacchiera elettronica",
    "system.wifi_bt": "Wi-Fi / Bluetooth", "system.shutdown": "Spegni", "system.reboot": "Riavvia",
    "system.exit": "Esci da PicoChess", "system.update": "Aggiorna PicoChess",
    "system.shutdown_confirm": "Spegnere il sistema?", "system.reboot_confirm": "Riavviare il sistema?",
    "system.sound_beep": "Suono (segnale)", "system.some": "Alcuni", "system.sample": "Esempio",
    "system.toggle_hotspot": "Attiva/disattiva hotspot", "system.toggle_bt": "Attiva/disattiva Bluetooth",
    "system.fix_bt": "Ripara Bluetooth", "system.system_info": "Informazioni sistema",
    "system.version": "Versione", "system.git_status": "Git", "system.local_ip": "IP (locale)",
    "system.external_ip": "IP (esterno)", "system.location": "Posizione", "system.battery": "Batteria",
    "system.mute": "Muto",
    "system.failed_voices": "Caricamento voci fallito",
    "system.playback_rate": "Velocità riproduzione (0 = minima, 9 = massima)", "system.slow": "lenta",
    "system.fast": "veloce", "system.step_of": "Passo {step} di 20",
    "system.retro_playback_speed": "Velocità di riproduzione del motore retro",
    "system.engine_features": "Funzioni motore: {features}", "system.windowed": "In finestra",
    "system.fullscreen": "Schermo intero", "system.clock_side": "Lato orologio",
    "system.notation": "Notazione", "system.confirm": "Conferma", "system.capital": "Maiuscole",
    "system.engine_name": "Nome motore", "system.ponder_seconds": "Secondi ponder",
}


# Keep every language catalog explicit and complete.  Terms that are product
# names or established chess/technical names may intentionally be identical to
# English; listing them here still gives translators an obvious editing point.
GERMAN.update({
    "common.engine": "Engine", "common.set": "Setzen", "common.standard": "Standard",
    "display.metal": "Metall", "display.soft": "Sanft", "engine.retro": "Retro",
    "game.elo": "Elo", "game.hint": "Tipp", "panel.picotutor": "PicoTutor",
    "position.chess960_frc": "Chess960 / FRC", "position.castling": "Rochade",
    "position.chess960": "Chess960", "position.standard_short": "Std",
    "position.sync_board": "Brett synchronisieren", "position.white_oo": "Weiß O-O",
    "position.white_ooo": "Weiß O-O-O", "position.black_oo": "Schwarz O-O",
    "position.black_ooo": "Schwarz O-O-O", "position.white_00": "Weiß 0-0",
    "position.white_000": "Weiß 0-0-0", "position.black_00": "Schwarz 0-0",
    "position.black_000": "Schwarz 0-0-0", "system.audio_help": (
        "Technische Einstellung. Wird für den nächsten PicoChess-Neustart gespeichert. "
        "Native ist für Wayland/PipeWire vorgesehen und benötigt pipewire-alsa. Wenn "
        "Native stumm bleibt, Installer erneut ausführen oder README lesen."
    ),
    "system.eboard": "E-Brett", "system.info": "Info", "system.max": "Maximum",
    "system.native_backend": "Native (Wayland / PipeWire)", "system.no_eboard": "Keines",
    "system.sox_backend": "SoX (X11 / älter)", "tile.engine": "Engine", "tile.system": "System",
    "tile.tutor": "Tutor", "time.blitz": "Blitz", "time.fischer": "Fischer",
    "time.nodes_k": "Knoten (k)", "tutor.deep_multipv": "Tiefes MultiPV",
    "tutor.depth": "d{depth}", "tutor.explorer": "Explorer", "tutor.hint": "Tipp",
    "tutor.lines": "{count} Varianten", "tutor.multipv": "MultiPV",
    "tutor.normal_threads": "Normal · 1×", "tutor.turbo_threads": "Turbo · {threads}×",
})

DUTCH.update({
    "common.black": "Zwart", "common.engine": "Engine", "common.set": "Instellen",
    "common.standard": "Standaard", "common.white": "Wit", "display.metal": "Metaal",
    "display.retro_touch": "Retro-aanraakscherm", "engine.retro": "Retro", "game.elo": "ELO",
    "game.hint": "Hint", "game.name": "Naam", "mode.hand": "Hand", "mode.ponder_on": "Ponderen aan",
    "panel.picotutor": "PicoTutor", "position.chess960_frc": "Chess960 / FRC",
    "position.select_pgn_move": "Selecteer PGN-zet", "position.castling": "Rokade",
    "position.chess960": "Chess960", "position.standard_short": "Std",
    "position.sync_board": "Bord synchroniseren", "position.white_oo": "Wit O-O",
    "position.white_ooo": "Wit O-O-O", "position.black_oo": "Zwart O-O",
    "position.black_ooo": "Zwart O-O-O", "position.white_00": "Wit 0-0",
    "position.white_000": "Wit 0-0-0", "position.black_00": "Zwart 0-0",
    "position.black_000": "Zwart 0-0-0", "system.audio_help": (
        "Technische instelling. Opgeslagen voor de volgende PicoChess-herstart. Native is "
        "bedoeld voor Wayland/PipeWire en vereist pipewire-alsa. Voer bij geen geluid het "
        "installatieprogramma opnieuw uit of lees de README."
    ),
    "system.computer_speaker": "Computerstem", "system.eboard": "E-bord", "system.info": "Info",
    "system.max": "Max", "system.native_backend": "Native (Wayland / PipeWire)",
    "system.native_backend_note": "Vereist pipewire-alsa · herstart PicoChess",
    "system.no_eboard": "Geen", "system.no_voices_language": "Geen stemmen gevonden voor taal {language}",
    "system.phone_off": "Telefoonluidspreker uit", "system.phone_on": "Telefoonluidspreker aan",
    "system.retro_info": "Retro-info", "system.settings_file": "Picochess.ini",
    "system.sox_backend": "SoX (X11 / verouderd)",
    "system.sox_backend_note": "Oudere afspeelbackend · herstart PicoChess",
    "system.user_speaker": "Spelerstem", "tile.engine": "Engine", "tile.tutor": "Tutor",
    "time.blitz": "Blitz", "time.fischer": "Fischer", "time.game_increment_short": "Partij + incr.",
    "time.min_game": "Min / partij", "time.nodes_k": "Knooppunten (k)",
    "time.search_plies": "Zoekdiepte", "time.sec_move": "Sec / zet", "time.value": "Waarde",
    "tutor.cpu": "Tutor-CPU", "tutor.deep_multipv": "Diepe MultiPV",
    "tutor.deep_threads": "Diepe Tutor-threads", "tutor.depth": "d{depth}",
    "tutor.explorer": "Verkenner", "tutor.hint": "Hint", "tutor.lines": "{count} lijnen",
    "tutor.multipv": "MultiPV", "tutor.normal_threads": "Normaal · 1×",
    "tutor.target_depth": "Doeldiepte", "tutor.turbo_threads": "Turbo · {threads}×",
})

FRENCH.update({
    "common.black": "Noirs", "common.engine": "Moteur", "common.set": "Définir",
    "common.standard": "Standard", "common.white": "Blancs", "display.metal": "Métal",
    "display.retro_touch": "Affichage tactile rétro", "engine.retro": "Rétro", "game.elo": "Elo",
    "game.hint": "Conseil", "game.name": "Nom", "mode.ponder_on": "Réflexion active",
    "panel.picotutor": "PicoTutor", "position.chess960_frc": "Chess960 / FRC",
    "position.select_pgn_move": "Sélectionnez un coup PGN", "position.castling": "Roque",
    "position.chess960": "Chess960", "position.standard_short": "Std",
    "position.sync_board": "Synchroniser l’échiquier", "position.white_oo": "Blancs O-O",
    "position.white_ooo": "Blancs O-O-O", "position.black_oo": "Noirs O-O",
    "position.black_ooo": "Noirs O-O-O", "position.white_00": "Blancs 0-0",
    "position.white_000": "Blancs 0-0-0", "position.black_00": "Noirs 0-0",
    "position.black_000": "Noirs 0-0-0", "system.audio_help": (
        "Réglage technique enregistré pour le prochain redémarrage de PicoChess. Native est "
        "prévu pour Wayland/PipeWire et nécessite pipewire-alsa. En l’absence de son, relancez "
        "l’installation ou consultez le README."
    ),
    "system.computer_speaker": "Voix ordinateur", "system.eboard": "Échiquier électronique",
    "system.info": "Infos", "system.max": "Max", "system.native_backend": "Natif (Wayland / PipeWire)",
    "system.native_backend_note": "Nécessite pipewire-alsa · redémarrer PicoChess",
    "system.no_eboard": "Aucun", "system.no_voices_language": "Aucune voix trouvée pour la langue {language}",
    "system.phone_off": "Haut-parleur du téléphone désactivé",
    "system.phone_on": "Haut-parleur du téléphone activé",
    "system.phone_stream_off": "Flux PicoTalker vers le téléphone désactivé",
    "system.phone_stream_on": "Flux PicoTalker vers le téléphone activé", "system.retro_info": "Infos rétro",
    "system.settings_file": "Picochess.ini", "system.sox_backend": "SoX (X11 / ancien)",
    "system.sox_backend_note": "Ancien moteur de lecture · redémarrer PicoChess",
    "system.user_speaker": "Voix joueur", "tile.engine": "Moteur", "tile.tutor": "Tuteur",
    "time.blitz": "Blitz", "time.fischer": "Fischer", "time.game_increment_short": "Partie + incr.",
    "time.min_game": "Min / partie", "time.nodes_k": "Nœuds (k)", "time.search_plies": "Demi-coups",
    "time.sec_move": "Sec / coup", "time.value": "Valeur", "tutor.cpu": "CPU du tuteur",
    "tutor.deep_multipv": "MultiPV profond", "tutor.deep_threads": "Threads profonds du tuteur",
    "tutor.depth": "p{depth}", "tutor.hint": "Conseil", "tutor.lines": "{count} variantes",
    "tutor.multipv": "MultiPV", "tutor.normal_threads": "Normal · 1×",
    "tutor.target_depth": "Profondeur cible", "tutor.turbo_threads": "Turbo · {threads}×",
})

SPANISH.update({
    "common.black": "Negras", "common.engine": "Motor", "common.set": "Fijar",
    "common.standard": "Estándar", "common.white": "Blancas", "display.metal": "Metal",
    "display.retro_touch": "Pantalla táctil retro", "engine.retro": "Retro", "game.elo": "ELO",
    "game.hint": "Pista", "game.name": "Nombre", "mode.ponder_on": "Ponderación activa",
    "panel.picotutor": "PicoTutor", "position.chess960_frc": "Chess960 / FRC",
    "position.select_pgn_move": "Seleccione una jugada PGN", "position.castling": "Enroque",
    "position.chess960": "Chess960", "position.standard_short": "Est.",
    "position.sync_board": "Sincronizar tablero", "position.white_oo": "Blancas O-O",
    "position.white_ooo": "Blancas O-O-O", "position.black_oo": "Negras O-O",
    "position.black_ooo": "Negras O-O-O", "position.white_00": "Blancas 0-0",
    "position.white_000": "Blancas 0-0-0", "position.black_00": "Negras 0-0",
    "position.black_000": "Negras 0-0-0", "system.audio_help": (
        "Ajuste técnico guardado para el próximo reinicio de PicoChess. Native está pensado "
        "para Wayland/PipeWire y necesita pipewire-alsa. Si no hay sonido, vuelva a ejecutar "
        "el instalador o consulte el README."
    ),
    "system.computer_speaker": "Voz del ordenador", "system.eboard": "Tablero electrónico",
    "system.info": "Información", "system.max": "Máx.", "system.native_backend": "Nativo (Wayland / PipeWire)",
    "system.native_backend_note": "Necesita pipewire-alsa · reiniciar PicoChess",
    "system.no_eboard": "Ninguno", "system.no_voices_language": "No hay voces para el idioma {language}",
    "system.phone_off": "Altavoz del teléfono desactivado", "system.phone_on": "Altavoz del teléfono activado",
    "system.phone_stream_off": "Transmisión PicoTalker al teléfono desactivada",
    "system.phone_stream_on": "Transmisión PicoTalker al teléfono activada",
    "system.retro_info": "Información retro",
    "system.settings_file": "Picochess.ini", "system.sox_backend": "SoX (X11 / antiguo)",
    "system.sox_backend_note": "Sistema de reproducción antiguo · reiniciar PicoChess",
    "system.user_speaker": "Voz del jugador", "tile.engine": "Motor", "tile.tutor": "Tutor",
    "time.blitz": "Blitz", "time.fischer": "Fischer", "time.game_increment_short": "Partida + inc.",
    "time.min_game": "Min / partida", "time.nodes_k": "Nodos (k)", "time.search_plies": "Semijugadas",
    "time.sec_move": "Seg / jugada", "time.value": "Valor", "tutor.cpu": "CPU del tutor",
    "tutor.deep_multipv": "MultiPV profundo", "tutor.deep_threads": "Hilos profundos del tutor",
    "tutor.depth": "p{depth}", "tutor.hint": "Pista", "tutor.lines": "{count} líneas",
    "tutor.multipv": "MultiPV", "tutor.normal_threads": "Normal · 1×",
    "tutor.target_depth": "Profundidad objetivo", "tutor.turbo_threads": "Turbo · {threads}×",
})

ITALIAN.update({
    "common.black": "Nero", "common.engine": "Motore", "common.set": "Imposta",
    "common.standard": "Standard", "common.white": "Bianco", "display.metal": "Metallo",
    "display.retro_touch": "Schermo touch retro", "engine.retro": "Retro", "game.elo": "ELO",
    "game.hint": "Suggerimento", "game.name": "Nome", "mode.ponder_on": "Ponder attivo",
    "panel.picotutor": "PicoTutor", "position.chess960_frc": "Chess960 / FRC",
    "position.select_pgn_move": "Seleziona una mossa PGN", "position.castling": "Arrocco",
    "position.chess960": "Chess960", "position.standard_short": "Std",
    "position.sync_board": "Sincronizza scacchiera", "position.white_oo": "Bianco O-O",
    "position.white_ooo": "Bianco O-O-O", "position.black_oo": "Nero O-O",
    "position.black_ooo": "Nero O-O-O", "position.white_00": "Bianco 0-0",
    "position.white_000": "Bianco 0-0-0", "position.black_00": "Nero 0-0",
    "position.black_000": "Nero 0-0-0", "system.audio_help": (
        "Impostazione tecnica salvata per il prossimo riavvio di PicoChess. Native è pensato "
        "per Wayland/PipeWire e richiede pipewire-alsa. Se non c’è audio, riesegui il programma "
        "di installazione o consulta il README."
    ),
    "system.computer_speaker": "Voce computer", "system.eboard": "Scacchiera elettronica",
    "system.info": "Info", "system.max": "Max", "system.native_backend": "Nativo (Wayland / PipeWire)",
    "system.native_backend_note": "Richiede pipewire-alsa · riavvia PicoChess",
    "system.no_eboard": "Nessuna", "system.no_voices_language": "Nessuna voce per la lingua {language}",
    "system.phone_off": "Altoparlante telefono disattivo", "system.phone_on": "Altoparlante telefono attivo",
    "system.phone_stream_off": "Stream PicoTalker al telefono disattivo",
    "system.phone_stream_on": "Stream PicoTalker al telefono attivo", "system.retro_info": "Info retro",
    "system.settings_file": "Picochess.ini", "system.sox_backend": "SoX (X11 / legacy)",
    "system.sox_backend_note": "Backend di riproduzione precedente · riavvia PicoChess",
    "system.user_speaker": "Voce giocatore", "tile.engine": "Motore", "tile.tutor": "Tutor",
    "time.blitz": "Blitz", "time.fischer": "Fischer", "time.game_increment_short": "Partita + incr.",
    "time.min_game": "Min / partita", "time.nodes_k": "Nodi (k)", "time.search_plies": "Semimosse",
    "time.sec_move": "Sec / mossa", "time.value": "Valore", "tutor.cpu": "CPU del Tutor",
    "tutor.deep_multipv": "MultiPV profondo", "tutor.deep_threads": "Thread profondi del Tutor",
    "tutor.depth": "p{depth}", "tutor.hint": "Suggerimento", "tutor.lines": "{count} linee",
    "tutor.multipv": "MultiPV", "tutor.normal_threads": "Normale · 1×",
    "tutor.target_depth": "Profondità obiettivo", "tutor.turbo_threads": "Turbo · {threads}×",
})


TRANSLATIONS = {
    "en": {},
    "de": GERMAN,
    "nl": DUTCH,
    "fr": FRENCH,
    "es": SPANISH,
    "it": ITALIAN,
}


def _fields(template: str) -> set[str]:
    return {name for _, name, _, _ in Formatter().parse(template) if name}


def get_menu_catalog(language: str) -> dict[str, str]:
    """Return the complete browser-menu catalog for *language*."""
    code = str(language or "en").lower()
    if code not in SUPPORTED_LANGUAGES:
        code = "en"
    return {**ENGLISH, **TRANSLATIONS[code]}


def get_menu_text(language: str, key: str, **values) -> str:
    """Return and optionally format one browser-menu translation."""
    template = get_menu_catalog(language).get(key, ENGLISH.get(key, key))
    return template.format(**values) if values else template


def get_menu_source_map(language: str) -> dict[str, str]:
    """Map English source phrases to localized phrases for the web client.

    The JavaScript overlay predates this catalog and contains English fallback
    strings.  Sending this derived map lets the client translate those strings
    while the editable source of truth remains the stable semantic-key catalog.
    """
    catalog = get_menu_catalog(language)
    source_map = {}
    for key, english in ENGLISH.items():
        source_map.setdefault(english, catalog[key])
    return source_map


def validate_catalogs() -> list[str]:
    """Return validation errors for language overrides and placeholders."""
    errors = []
    for language, overrides in TRANSLATIONS.items():
        unknown = sorted(set(overrides) - set(ENGLISH))
        for key in unknown:
            errors.append(f"{language}: unknown key {key}")
        for key, translated in overrides.items():
            if _fields(translated) != _fields(ENGLISH[key]):
                errors.append(f"{language}: placeholder mismatch for {key}")
    return errors
